package com.wook.ex;

import java.io.Serializable;
import java.util.Date;

/**
 * 근무표 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TimeTableS implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 근무표식별키. */
	private Integer timeKey;

	/** 회사. */
	private CompanyS company;

	/** 회사구성원. */
	private CompanyPersonS companyPerson;

	/** 근무일자. */
	private Date workingDate;

	/** working_start. */
	private Integer workingStart;

	/** working_end. */
	private Integer workingEnd;

	/**
	 * 생성자.
	 */
	public TimeTableS() {
	}

	/**
	 * 근무표식별키을 설정합니다..
	 * 
	 * @param timeKey
	 *            근무표식별키
	 */
	public void setTimeKey(Integer timeKey) {
		this.timeKey = timeKey;
	}

	/**
	 * 근무표식별키을 가져옵니다..
	 * 
	 * @return 근무표식별키
	 */
	public Integer getTimeKey() {
		return this.timeKey;
	}

	/**
	 * 회사을 설정합니다..
	 * 
	 * @param company
	 *            회사
	 */
	public void setCompany(CompanyS company) {
		this.company = company;
	}

	/**
	 * 회사을 가져옵니다..
	 * 
	 * @return 회사
	 */
	public CompanyS getCompany() {
		return this.company;
	}

	/**
	 * 회사구성원을 설정합니다..
	 * 
	 * @param companyPerson
	 *            회사구성원
	 */
	public void setCompanyPerson(CompanyPersonS companyPerson) {
		this.companyPerson = companyPerson;
	}

	/**
	 * 회사구성원을 가져옵니다..
	 * 
	 * @return 회사구성원
	 */
	public CompanyPersonS getCompanyPerson() {
		return this.companyPerson;
	}

	/**
	 * 근무일자을 설정합니다..
	 * 
	 * @param workingDate
	 *            근무일자
	 */
	public void setWorkingDate(Date workingDate) {
		this.workingDate = workingDate;
	}

	/**
	 * 근무일자을 가져옵니다..
	 * 
	 * @return 근무일자
	 */
	public Date getWorkingDate() {
		return this.workingDate;
	}

	/**
	 * working_start을 설정합니다..
	 * 
	 * @param workingStart
	 *            working_start
	 */
	public void setWorkingStart(Integer workingStart) {
		this.workingStart = workingStart;
	}

	/**
	 * working_start을 가져옵니다..
	 * 
	 * @return working_start
	 */
	public Integer getWorkingStart() {
		return this.workingStart;
	}

	/**
	 * working_end을 설정합니다..
	 * 
	 * @param workingEnd
	 *            working_end
	 */
	public void setWorkingEnd(Integer workingEnd) {
		this.workingEnd = workingEnd;
	}

	/**
	 * working_end을 가져옵니다..
	 * 
	 * @return working_end
	 */
	public Integer getWorkingEnd() {
		return this.workingEnd;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((timeKey == null) ? 0 : timeKey.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TimeTableS other = (TimeTableS) obj;
		if (timeKey == null) {
			if (other.timeKey != null) {
				return false;
			}
		} else if (!timeKey.equals(other.timeKey)) {
			return false;
		}
		return true;
	}

}
