package com.wook.ex;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BcommentS implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글번호. */
	private Integer commentNumber;

	/** 회원. */
	private UsersS users;

	/** 게시글내용. */
	private String commentContent;

	/** 작성일자. */
	private Date regDate;

	/** 게시글종류. */
	private Integer flag;

	/** 댓글 목록. */
	private Set<ReplyS> replySet;

	/**
	 * 생성자.
	 */
	public BcommentS() {
		this.replySet = new HashSet<ReplyS>();
	}

	/**
	 * 게시글번호을 설정합니다..
	 * 
	 * @param commentNumber
	 *            게시글번호
	 */
	public void setCommentNumber(Integer commentNumber) {
		this.commentNumber = commentNumber;
	}

	/**
	 * 게시글번호을 가져옵니다..
	 * 
	 * @return 게시글번호
	 */
	public Integer getCommentNumber() {
		return this.commentNumber;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param users
	 *            회원
	 */
	public void setUsers(UsersS users) {
		this.users = users;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public UsersS getUsers() {
		return this.users;
	}

	/**
	 * 게시글내용을 설정합니다..
	 * 
	 * @param commentContent
	 *            게시글내용
	 */
	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	/**
	 * 게시글내용을 가져옵니다..
	 * 
	 * @return 게시글내용
	 */
	public String getCommentContent() {
		return this.commentContent;
	}

	/**
	 * 작성일자을 설정합니다..
	 * 
	 * @param regDate
	 *            작성일자
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * 작성일자을 가져옵니다..
	 * 
	 * @return 작성일자
	 */
	public Date getRegDate() {
		return this.regDate;
	}

	/**
	 * 게시글종류을 설정합니다..
	 * 
	 * @param flag
	 *            게시글종류
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * 게시글종류을 가져옵니다..
	 * 
	 * @return 게시글종류
	 */
	public Integer getFlag() {
		return this.flag;
	}

	/**
	 * 댓글 목록을 설정합니다..
	 * 
	 * @param replySet
	 *            댓글 목록
	 */
	public void setReplySet(Set<ReplyS> replySet) {
		this.replySet = replySet;
	}

	/**
	 * 댓글를 추가합니다..
	 * 
	 * @param reply
	 *            댓글
	 */
	public void addReply(ReplyS reply) {
		this.replySet.add(reply);
	}

	/**
	 * 댓글 목록을 가져옵니다..
	 * 
	 * @return 댓글 목록
	 */
	public Set<ReplyS> getReplySet() {
		return this.replySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commentNumber == null) ? 0 : commentNumber.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BcommentS other = (BcommentS) obj;
		if (commentNumber == null) {
			if (other.commentNumber != null) {
				return false;
			}
		} else if (!commentNumber.equals(other.commentNumber)) {
			return false;
		}
		return true;
	}

}
