package com.wook.ex;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 회사 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyS implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회사코드. */
	private Integer companyCode;

	/** company_name. */
	private String companyName;

	/** 회사전화번호. */
	private String companyTel;

	/** 주말수당. */
	private Float holidayComm;

	/** 야간수당. */
	private Float nightComm;

	/** 근무표 목록. */
	private Set<TimeTableS> timeTableSet;

	/** 회사구성원 목록. */
	private Set<CompanyPersonS> companyPersonSet;

	/**
	 * 생성자.
	 */
	public CompanyS() {
		this.companyPersonSet = new HashSet<CompanyPersonS>();
		this.timeTableSet = new HashSet<TimeTableS>();
	}

	/**
	 * 회사코드을 설정합니다..
	 * 
	 * @param companyCode
	 *            회사코드
	 */
	public void setCompanyCode(Integer companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * 회사코드을 가져옵니다..
	 * 
	 * @return 회사코드
	 */
	public Integer getCompanyCode() {
		return this.companyCode;
	}

	/**
	 * company_name을 설정합니다..
	 * 
	 * @param companyName
	 *            company_name
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * company_name을 가져옵니다..
	 * 
	 * @return company_name
	 */
	public String getCompanyName() {
		return this.companyName;
	}

	/**
	 * 회사전화번호을 설정합니다..
	 * 
	 * @param companyTel
	 *            회사전화번호
	 */
	public void setCompanyTel(String companyTel) {
		this.companyTel = companyTel;
	}

	/**
	 * 회사전화번호을 가져옵니다..
	 * 
	 * @return 회사전화번호
	 */
	public String getCompanyTel() {
		return this.companyTel;
	}

	/**
	 * 주말수당을 설정합니다..
	 * 
	 * @param holidayComm
	 *            주말수당
	 */
	public void setHolidayComm(Float holidayComm) {
		this.holidayComm = holidayComm;
	}

	/**
	 * 주말수당을 가져옵니다..
	 * 
	 * @return 주말수당
	 */
	public Float getHolidayComm() {
		return this.holidayComm;
	}

	/**
	 * 야간수당을 설정합니다..
	 * 
	 * @param nightComm
	 *            야간수당
	 */
	public void setNightComm(Float nightComm) {
		this.nightComm = nightComm;
	}

	/**
	 * 야간수당을 가져옵니다..
	 * 
	 * @return 야간수당
	 */
	public Float getNightComm() {
		return this.nightComm;
	}

	/**
	 * 근무표 목록을 설정합니다..
	 * 
	 * @param timeTableSet
	 *            근무표 목록
	 */
	public void setTimeTableSet(Set<TimeTableS> timeTableSet) {
		this.timeTableSet = timeTableSet;
	}

	/**
	 * 근무표를 추가합니다..
	 * 
	 * @param timeTable
	 *            근무표
	 */
	public void addTimeTable(TimeTableS timeTable) {
		this.timeTableSet.add(timeTable);
	}

	/**
	 * 근무표 목록을 가져옵니다..
	 * 
	 * @return 근무표 목록
	 */
	public Set<TimeTableS> getTimeTableSet() {
		return this.timeTableSet;
	}

	/**
	 * 회사구성원 목록을 설정합니다..
	 * 
	 * @param companyPersonSet
	 *            회사구성원 목록
	 */
	public void setCompanyPersonSet(Set<CompanyPersonS> companyPersonSet) {
		this.companyPersonSet = companyPersonSet;
	}

	/**
	 * 회사구성원를 추가합니다..
	 * 
	 * @param companyPerson
	 *            회사구성원
	 */
	public void addCompanyPerson(CompanyPersonS companyPerson) {
		this.companyPersonSet.add(companyPerson);
	}

	/**
	 * 회사구성원 목록을 가져옵니다..
	 * 
	 * @return 회사구성원 목록
	 */
	public Set<CompanyPersonS> getCompanyPersonSet() {
		return this.companyPersonSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((companyCode == null) ? 0 : companyCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompanyS other = (CompanyS) obj;
		if (companyCode == null) {
			if (other.companyCode != null) {
				return false;
			}
		} else if (!companyCode.equals(other.companyCode)) {
			return false;
		}
		return true;
	}

}
