package com.wook.ex;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 회사구성원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyPersonS implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 직원코드. */
	private Integer memberId;

	/** 회사. */
	private CompanyS company;

	/** 회원. */
	private UsersS users;

	/** 시급. */
	private Integer salary;

	/** 직급. */
	private String grade;

	/** 입사일자. */
	private Date hireDate;

	/** 근무표 목록. */
	private Set<TimeTableS> timeTableSet;

	/**
	 * 생성자.
	 */
	public CompanyPersonS() {
		this.timeTableSet = new HashSet<TimeTableS>();
	}

	/**
	 * 직원코드을 설정합니다..
	 * 
	 * @param memberId
	 *            직원코드
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * 직원코드을 가져옵니다..
	 * 
	 * @return 직원코드
	 */
	public Integer getMemberId() {
		return this.memberId;
	}

	/**
	 * 회사을 설정합니다..
	 * 
	 * @param company
	 *            회사
	 */
	public void setCompany(CompanyS company) {
		this.company = company;
	}

	/**
	 * 회사을 가져옵니다..
	 * 
	 * @return 회사
	 */
	public CompanyS getCompany() {
		return this.company;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param users
	 *            회원
	 */
	public void setUsers(UsersS users) {
		this.users = users;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public UsersS getUsers() {
		return this.users;
	}

	/**
	 * 시급을 설정합니다..
	 * 
	 * @param salary
	 *            시급
	 */
	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	/**
	 * 시급을 가져옵니다..
	 * 
	 * @return 시급
	 */
	public Integer getSalary() {
		return this.salary;
	}

	/**
	 * 직급을 설정합니다..
	 * 
	 * @param grade
	 *            직급
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * 직급을 가져옵니다..
	 * 
	 * @return 직급
	 */
	public String getGrade() {
		return this.grade;
	}

	/**
	 * 입사일자을 설정합니다..
	 * 
	 * @param hireDate
	 *            입사일자
	 */
	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	/**
	 * 입사일자을 가져옵니다..
	 * 
	 * @return 입사일자
	 */
	public Date getHireDate() {
		return this.hireDate;
	}

	/**
	 * 근무표 목록을 설정합니다..
	 * 
	 * @param timeTableSet
	 *            근무표 목록
	 */
	public void setTimeTableSet(Set<TimeTableS> timeTableSet) {
		this.timeTableSet = timeTableSet;
	}

	/**
	 * 근무표를 추가합니다..
	 * 
	 * @param timeTable
	 *            근무표
	 */
	public void addTimeTable(TimeTableS timeTable) {
		this.timeTableSet.add(timeTable);
	}

	/**
	 * 근무표 목록을 가져옵니다..
	 * 
	 * @return 근무표 목록
	 */
	public Set<TimeTableS> getTimeTableSet() {
		return this.timeTableSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((memberId == null) ? 0 : memberId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompanyPersonS other = (CompanyPersonS) obj;
		if (memberId == null) {
			if (other.memberId != null) {
				return false;
			}
		} else if (!memberId.equals(other.memberId)) {
			return false;
		}
		return true;
	}

}
