package com.wook.ex;

import java.io.Serializable;
import java.util.Date;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReplyS implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글번호. */
	private Integer replyNumber;

	/** 회원. */
	private UsersS users;

	/** 게시판. */
	private BcommentS bcomment;

	/** 댓글내용. */
	private String replyContent;

	/** reg_date. */
	private Date regDate;

	/**
	 * 생성자.
	 */
	public ReplyS() {
	}

	/**
	 * 댓글번호을 설정합니다..
	 * 
	 * @param replyNumber
	 *            댓글번호
	 */
	public void setReplyNumber(Integer replyNumber) {
		this.replyNumber = replyNumber;
	}

	/**
	 * 댓글번호을 가져옵니다..
	 * 
	 * @return 댓글번호
	 */
	public Integer getReplyNumber() {
		return this.replyNumber;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param users
	 *            회원
	 */
	public void setUsers(UsersS users) {
		this.users = users;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public UsersS getUsers() {
		return this.users;
	}

	/**
	 * 게시판을 설정합니다..
	 * 
	 * @param bcomment
	 *            게시판
	 */
	public void setBcomment(BcommentS bcomment) {
		this.bcomment = bcomment;
	}

	/**
	 * 게시판을 가져옵니다..
	 * 
	 * @return 게시판
	 */
	public BcommentS getBcomment() {
		return this.bcomment;
	}

	/**
	 * 댓글내용을 설정합니다..
	 * 
	 * @param replyContent
	 *            댓글내용
	 */
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	/**
	 * 댓글내용을 가져옵니다..
	 * 
	 * @return 댓글내용
	 */
	public String getReplyContent() {
		return this.replyContent;
	}

	/**
	 * reg_date을 설정합니다..
	 * 
	 * @param regDate
	 *            reg_date
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * reg_date을 가져옵니다..
	 * 
	 * @return reg_date
	 */
	public Date getRegDate() {
		return this.regDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((replyNumber == null) ? 0 : replyNumber.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReplyS other = (ReplyS) obj;
		if (replyNumber == null) {
			if (other.replyNumber != null) {
				return false;
			}
		} else if (!replyNumber.equals(other.replyNumber)) {
			return false;
		}
		return true;
	}

}
